name: Build docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - id: maintag
        name: Main tag hack
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo "::set-output name=pythontag::ghcr.io/khwilson/tester-python:$VERSION"
          echo "::set-output name=rtag::ghcr.io/khwilson/tester-r:$VERSION"

      - name: Build python docker image
        uses: docker/build-push-action@v2
        with:
          file: ./python/Dockerfile
          context: ./python
          push: true
          tags: ${{ steps.maintag.outputs.pythontag }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          file: ./r/Dockerfile
          context: ./r
          push: true
          tags: ${{ steps.maintag.outputs.rtag }}
